language: ruby
rvm:
  - 2.0.0
env:
  SECRET_KEY_BASE="$(bundle exec rake secret)"
before_install:
  - npm install jshint
install:
  - bundle install
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - rubocop -D
  - travis lint --skip-completion-check
  - jshint app/assets/javascripts
  - bundle exec rake
