language: ruby
cache: bundler
rvm:
  - 2.0.0
env:
  secure: "EjyjRR+dJPDV5n7vypLLVjQcv3NEUGpq1aqoiU+idERE9qFw5GRPu9JPzTZ2ECjGqr6W506H4hu9ai0JbJKyzZpzaMb0wks7zQiJNHPqlFq5tlo3V+tTS10aop2HivLHOmUVE6bQEHz7Jwv7cRqJcrenA5HtqSahU20zuQq5GMc="
before_install:
  - npm install jshint
install:
  - bundle install
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - rubocop -D
  - travis lint --skip-completion-check
  - bundle exec rake jshint
  - bundle exec rake
